#!/bin/bash
# Auto-generates .claude/AGENTS.md — a project operational guide
# Detects project type, build/test/lint commands, and writes them out
# so Ralph iterations (and humans) know how to operate this project.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
OUTPUT_FILE="${PROJECT_DIR}/.claude/AGENTS.md"

mkdir -p "$(dirname "$OUTPUT_FILE")"

# ── Project type detection (mirrors hooks/lint-on-stop.sh) ──────────────

detect_project() {
  local type="unknown"
  local lang=""
  local framework=""
  local build_cmd=""
  local test_cmd=""
  local lint_cmd=""
  local format_cmd=""
  local run_cmd=""

  # Elixir / Phoenix
  if [ -f "${PROJECT_DIR}/mix.exs" ]; then
    type="elixir"
    lang="Elixir"
    build_cmd="mix compile"
    test_cmd="mix test"
    lint_cmd="mix credo"
    format_cmd="mix format"
    if grep -q "phoenix" "${PROJECT_DIR}/mix.exs" 2>/dev/null; then
      framework="Phoenix"
      run_cmd="mix phx.server"
    fi
    if grep -q "dialyxir" "${PROJECT_DIR}/mix.exs" 2>/dev/null; then
      lint_cmd="mix credo && mix dialyzer"
    fi
  # Python
  elif [ -f "${PROJECT_DIR}/pyproject.toml" ] || [ -f "${PROJECT_DIR}/setup.py" ]; then
    type="python"
    lang="Python"
    if [ -f "${PROJECT_DIR}/pyproject.toml" ]; then
      # Check for uv vs pip
      if command -v uv >/dev/null 2>&1; then
        build_cmd="uv sync"
        test_cmd="uv run pytest"
        lint_cmd="uv run ruff check ."
        format_cmd="uv run ruff format ."
      else
        build_cmd="pip install -e ."
        test_cmd="pytest"
        lint_cmd="ruff check ."
        format_cmd="ruff format ."
      fi
      if grep -q "basedpyright\|pyright" "${PROJECT_DIR}/pyproject.toml" 2>/dev/null; then
        lint_cmd="${lint_cmd} && uv run basedpyright"
      fi
    fi
    if [ -f "${PROJECT_DIR}/manage.py" ]; then
      framework="Django"
      run_cmd="python manage.py runserver"
    elif grep -q "fastapi\|FastAPI" "${PROJECT_DIR}/pyproject.toml" 2>/dev/null; then
      framework="FastAPI"
      run_cmd="uvicorn main:app --reload"
    elif grep -q "flask\|Flask" "${PROJECT_DIR}/pyproject.toml" 2>/dev/null; then
      framework="Flask"
      run_cmd="flask run"
    fi
  # Node.js / TypeScript
  elif [ -f "${PROJECT_DIR}/package.json" ]; then
    type="node"
    if [ -f "${PROJECT_DIR}/tsconfig.json" ]; then
      lang="TypeScript"
    else
      lang="JavaScript"
    fi
    # Detect package manager
    local pm="npm"
    [ -f "${PROJECT_DIR}/pnpm-lock.yaml" ] && pm="pnpm"
    [ -f "${PROJECT_DIR}/yarn.lock" ] && pm="yarn"
    [ -f "${PROJECT_DIR}/bun.lockb" ] && pm="bun"

    build_cmd="${pm} run build"
    test_cmd="${pm} test"
    lint_cmd="${pm} run lint"
    format_cmd="${pm} run format"

    # Check package.json for scripts that exist
    if command -v jq >/dev/null 2>&1 && [ -f "${PROJECT_DIR}/package.json" ]; then
      local scripts
      scripts=$(jq -r '.scripts // {} | keys[]' "${PROJECT_DIR}/package.json" 2>/dev/null || true)
      echo "$scripts" | grep -q "^build$" || build_cmd=""
      echo "$scripts" | grep -q "^test$" || test_cmd=""
      echo "$scripts" | grep -q "^lint$" || lint_cmd=""
      echo "$scripts" | grep -q "^format$" || format_cmd=""
      echo "$scripts" | grep -q "^dev$" && run_cmd="${pm} run dev"
      echo "$scripts" | grep -q "^start$" && [ -z "$run_cmd" ] && run_cmd="${pm} start"
    fi

    # Framework detection
    if [ -f "${PROJECT_DIR}/next.config.js" ] || [ -f "${PROJECT_DIR}/next.config.mjs" ] || [ -f "${PROJECT_DIR}/next.config.ts" ]; then
      framework="Next.js"
    elif [ -f "${PROJECT_DIR}/nuxt.config.ts" ]; then
      framework="Nuxt"
    fi
  # Go
  elif [ -f "${PROJECT_DIR}/go.mod" ]; then
    type="go"
    lang="Go"
    build_cmd="go build ./..."
    test_cmd="go test ./..."
    lint_cmd="golangci-lint run"
    format_cmd="gofmt -w ."
    run_cmd="go run ."
  # Rust
  elif [ -f "${PROJECT_DIR}/Cargo.toml" ]; then
    type="rust"
    lang="Rust"
    build_cmd="cargo build"
    test_cmd="cargo test"
    lint_cmd="cargo clippy"
    format_cmd="cargo fmt"
    run_cmd="cargo run"
  fi

  # ── Write AGENTS.md ──────────────────────────────────────────────────

  cat > "$OUTPUT_FILE" << AGENTS_EOF
# Project Operations Guide

> Auto-generated by \`generate-agents-md.sh\` — re-run to refresh.

## Project Type

- **Language:** ${lang:-Unknown}
- **Framework:** ${framework:-None detected}
- **Type identifier:** ${type}

## Commands

| Action  | Command |
|---------|---------|
| Build   | \`${build_cmd:-N/A}\` |
| Test    | \`${test_cmd:-N/A}\` |
| Lint    | \`${lint_cmd:-N/A}\` |
| Format  | \`${format_cmd:-N/A}\` |
| Run     | \`${run_cmd:-N/A}\` |

## Workflow Rules

1. **Always run tests** before committing: \`${test_cmd:-echo "no test command detected"}\`
2. **Always run lint** before committing: \`${lint_cmd:-echo "no lint command detected"}\`
3. **Format code** before committing: \`${format_cmd:-echo "no format command detected"}\`
4. Tests and lint must pass — do not commit with failures.

## Git Conventions

- Write descriptive commit messages (imperative mood, explain the "why")
- One logical change per commit
- Keep commits atomic and self-contained

## Notes

- If commands above show N/A, detect manually and update this file
- This file is used by Ralph loop iterations as the project operational guide
AGENTS_EOF

  echo "Generated ${OUTPUT_FILE}"
  echo "Project type: ${type} | Language: ${lang:-unknown} | Framework: ${framework:-none}"
}

detect_project
