#!/usr/bin/env bash
#
# setup-aliases.sh — Generate shell aliases for quick worktree hopping
#
# Generates za, zb, zc, ... aliases that cd into worktrees under .claude/worktrees/
# Supports bash, zsh, and fish shells.
#
# Usage:
#   ./scripts/setup-aliases.sh              # Auto-detect shell, print aliases
#   ./scripts/setup-aliases.sh --fish       # Generate fish functions
#   ./scripts/setup-aliases.sh --bash       # Generate bash/zsh aliases
#   ./scripts/setup-aliases.sh --install    # Append to shell config file

set -euo pipefail

WORKTREE_DIR=".claude/worktrees"
LETTERS=(a b c d e f)
MAX_WORKTREES=6

# Detect shell
detect_shell() {
  if [[ "${1:-}" == "--fish" ]]; then
    echo "fish"
  elif [[ "${1:-}" == "--bash" ]]; then
    echo "bash"
  elif [[ -n "${FISH_VERSION:-}" ]]; then
    echo "fish"
  elif [[ "$(basename "${SHELL:-/bin/bash}")" == "fish" ]]; then
    echo "fish"
  else
    echo "bash"
  fi
}

# Get the repo root
get_repo_root() {
  git rev-parse --show-toplevel 2>/dev/null || {
    echo "Error: Not in a git repository" >&2
    exit 1
  }
}

# Generate bash/zsh aliases
generate_bash_aliases() {
  local repo_root
  repo_root=$(get_repo_root)
  local base="${repo_root}/${WORKTREE_DIR}"

  cat <<'HEADER'
# Worktree hopping aliases (generated by agentic-coding-workflow)
# Add to ~/.bashrc or ~/.zshrc

# z0 — jump back to main worktree
alias z0='cd "$(git rev-parse --show-toplevel)"'

HEADER

  # Static aliases that dynamically resolve worktrees
  cat <<'ALIASES'
# za-zf — jump to worktrees by index (alphabetical order)
_worktree_cd() {
  local idx="$1"
  local root
  root=$(git rev-parse --show-toplevel 2>/dev/null) || { echo "Not in a git repo"; return 1; }
  local base="${root}/.claude/worktrees"
  if [[ ! -d "$base" ]]; then
    echo "No worktrees found at ${base}"
    return 1
  fi
  local dirs=()
  while IFS= read -r d; do
    dirs+=("$d")
  done < <(find "$base" -mindepth 1 -maxdepth 1 -type d | sort)
  if [[ ${#dirs[@]} -eq 0 ]]; then
    echo "No worktrees in ${base}"
    return 1
  fi
  if [[ $idx -ge ${#dirs[@]} ]]; then
    echo "Only ${#dirs[@]} worktrees available (0-$((${#dirs[@]}-1)))"
    return 1
  fi
  echo "Switching to: ${dirs[$idx]}"
  cd "${dirs[$idx]}"
}

alias za='_worktree_cd 0'
alias zb='_worktree_cd 1'
alias zc='_worktree_cd 2'
alias zd='_worktree_cd 3'
alias ze='_worktree_cd 4'
alias zf='_worktree_cd 5'

# zls — list all worktrees with their aliases
zls() {
  local root
  root=$(git rev-parse --show-toplevel 2>/dev/null) || { echo "Not in a git repo"; return 1; }
  local base="${root}/.claude/worktrees"
  if [[ ! -d "$base" ]]; then
    echo "No worktrees at ${base}"
    return 0
  fi
  local letters=(a b c d e f)
  local i=0
  echo "Worktree aliases:"
  while IFS= read -r d; do
    local branch
    branch=$(git -C "$d" branch --show-current 2>/dev/null || echo "detached")
    printf "  z%s → %s (%s)\n" "${letters[$i]}" "$(basename "$d")" "$branch"
    ((i++))
  done < <(find "$base" -mindepth 1 -maxdepth 1 -type d | sort)
  echo "  z0 → main worktree"
}
ALIASES
}

# Generate fish functions
generate_fish_functions() {
  cat <<'FISH'
# Worktree hopping functions for fish shell (generated by agentic-coding-workflow)
# Add to ~/.config/fish/conf.d/worktree-aliases.fish

# z0 — jump back to main worktree
function z0
  cd (git rev-parse --show-toplevel)
end

# Helper: cd to worktree by index
function _worktree_cd
  set -l idx $argv[1]
  set -l root (git rev-parse --show-toplevel 2>/dev/null)
  or begin; echo "Not in a git repo"; return 1; end

  set -l base "$root/.claude/worktrees"
  if not test -d "$base"
    echo "No worktrees found at $base"
    return 1
  end

  set -l dirs (find "$base" -mindepth 1 -maxdepth 1 -type d | sort)
  if test (count $dirs) -eq 0
    echo "No worktrees in $base"
    return 1
  end

  # fish arrays are 1-indexed
  set -l fish_idx (math $idx + 1)
  if test $fish_idx -gt (count $dirs)
    echo "Only "(count $dirs)" worktrees available (a-"(string sub -l 1 (string repeat -n (count $dirs) "abcdef"))")"
    return 1
  end

  echo "Switching to: $dirs[$fish_idx]"
  cd $dirs[$fish_idx]
end

function za; _worktree_cd 0; end
function zb; _worktree_cd 1; end
function zc; _worktree_cd 2; end
function zd; _worktree_cd 3; end
function ze; _worktree_cd 4; end
function zf; _worktree_cd 5; end

# zls — list all worktrees with their aliases
function zls
  set -l root (git rev-parse --show-toplevel 2>/dev/null)
  or begin; echo "Not in a git repo"; return 1; end

  set -l base "$root/.claude/worktrees"
  if not test -d "$base"
    echo "No worktrees at $base"
    return 0
  end

  set -l letters a b c d e f
  set -l i 1
  echo "Worktree aliases:"
  for d in (find "$base" -mindepth 1 -maxdepth 1 -type d | sort)
    set -l branch (git -C "$d" branch --show-current 2>/dev/null; or echo "detached")
    printf "  z%s → %s (%s)\n" $letters[$i] (basename "$d") "$branch"
    set i (math $i + 1)
  end
  echo "  z0 → main worktree"
end
FISH
}

# Install to shell config
install_aliases() {
  local shell_type
  shell_type=$(detect_shell "${1:-}")

  if [[ "$shell_type" == "fish" ]]; then
    local config_dir="${HOME}/.config/fish/conf.d"
    local config_file="${config_dir}/worktree-aliases.fish"
    mkdir -p "$config_dir"
    generate_fish_functions > "$config_file"
    echo "Installed fish functions to ${config_file}"
    echo "Run: source ${config_file}"
  else
    local config_file="${HOME}/.bashrc"
    [[ "$(basename "${SHELL:-}")" == "zsh" ]] && config_file="${HOME}/.zshrc"
    echo "" >> "$config_file"
    generate_bash_aliases >> "$config_file"
    echo "Appended aliases to ${config_file}"
    echo "Run: source ${config_file}"
  fi
}

# Main
main() {
  local shell_type
  shell_type=$(detect_shell "${1:-}")

  if [[ "${1:-}" == "--install" ]]; then
    install_aliases "${2:-}"
    exit 0
  fi

  echo "# Shell: ${shell_type}"
  echo "# Run with --install to add to your shell config"
  echo ""

  if [[ "$shell_type" == "fish" ]]; then
    generate_fish_functions
  else
    generate_bash_aliases
  fi
}

main "$@"
